name: Test Python code

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: True

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        channel-priority: [strict]
        include:
          - python-version: "3.11"
            os: macos-latest
          - python-version: "3.11"
            os: windows-latest
          - python-version: "3.11"
            os: ubuntu-latest
            channel-priority: flexible
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache conda packages
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('.github/environment.yml') }}

      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          channel-priority: ${{ matrix.channel-priority }}
          environment-file: .github/environment.yml

      - name: Install package in development mode
        shell: bash -l {0}
        run: python -m pip install --upgrade-strategy=only-if-needed -e .[display,testing]

      - name: Run unit tests
        shell: bash -l {0}
        run: pytest --cov=mir_eval
        working-directory: tests
